In [1]:
# never use the library or module name as file path 

### Numpy
- it works like list
- much faster and reliable than list
- mostly work in 1d ,2d and 3d arrays


In [2]:
import numpy as np
a= np.array([34,34,345,2345,12,45,0])
print(a)
print(type(a))

[  34   34  345 2345   12   45    0]
<class 'numpy.ndarray'>


In [3]:
a=np.array([34,34,345,2345,12,45,0])
b=np.array([[34,34,345,2345,12,45],[9,34,4,5,62,3,234,432,345],[9,34,4,5,62,3,234,432,345]])
b

<ipython-input-3-5f26217e5e6c>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[34,34,345,2345,12,45],[9,34,4,5,62,3,234,432,345],[9,34,4,5,62,3,234,432,345]])


array([list([34, 34, 345, 2345, 12, 45]),
       list([9, 34, 4, 5, 62, 3, 234, 432, 345]),
       list([9, 34, 4, 5, 62, 3, 234, 432, 345])], dtype=object)

In [4]:
# docuemntation link:  https://numpy.org/doc/1.23/user/absolute_beginners.html

a=np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
a[0]   # it will extract the first set of array

array([1, 2, 3, 4])

In [7]:
b=a[0]
b[0]   #it takes the first value in first array

1

In [8]:
# to create zeros and ones in an array
print(np.zeros(3))
print(np.ones(3))

[0. 0. 0.]
[1. 1. 1.]


In [9]:
# operands like +-*/ can only work on same number of values or formation

c=np.zeros(4)+np.ones(4)
c

array([1., 1., 1., 1.])

In [10]:
d=np.zeros(4)*np.ones(4)
d

array([0., 0., 0., 0.])

In [11]:
# can create array of different ranges
print(np.arange(1,11))
print(np.arange(0,11, 2)) # it can also creates difference of interval like will print after 2 values
print(np.arange(0,13, 3)) # we can print the table as wellb


[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]
[ 0  3  6  9 12]


In [12]:
import numpy as np
np.arange(0,33,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [13]:
# we can generate any sequence of number in any range
np.linspace(0,10 ,num=12)
e=np.linspace(1,33, num=78)
e
# len(e)


array([ 1.        ,  1.41558442,  1.83116883,  2.24675325,  2.66233766,
        3.07792208,  3.49350649,  3.90909091,  4.32467532,  4.74025974,
        5.15584416,  5.57142857,  5.98701299,  6.4025974 ,  6.81818182,
        7.23376623,  7.64935065,  8.06493506,  8.48051948,  8.8961039 ,
        9.31168831,  9.72727273, 10.14285714, 10.55844156, 10.97402597,
       11.38961039, 11.80519481, 12.22077922, 12.63636364, 13.05194805,
       13.46753247, 13.88311688, 14.2987013 , 14.71428571, 15.12987013,
       15.54545455, 15.96103896, 16.37662338, 16.79220779, 17.20779221,
       17.62337662, 18.03896104, 18.45454545, 18.87012987, 19.28571429,
       19.7012987 , 20.11688312, 20.53246753, 20.94805195, 21.36363636,
       21.77922078, 22.19480519, 22.61038961, 23.02597403, 23.44155844,
       23.85714286, 24.27272727, 24.68831169, 25.1038961 , 25.51948052,
       25.93506494, 26.35064935, 26.76623377, 27.18181818, 27.5974026 ,
       28.01298701, 28.42857143, 28.84415584, 29.25974026, 29.67

In [14]:
# concatenation of two array
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a,b
c=np.concatenate((a,b))
c


array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
# to create the square of whole list
np.square(b)


array([25, 36, 49, 64], dtype=int32)

In [16]:
# how to find the shape and size of an array
array1=np.array([1,2,3,4,5])
array2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
array3=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(array1)
print(array2)
print(array3)


[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [17]:
# tp check the dimension size and shape
print(array3.ndim)   #dimension
print(array3.shape)  # need to learn
print(array3.size)   #number of values 

3
(1, 3, 5)
15


In [18]:
np.zeros((4,5))
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# how to reshape an array
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
five_up = (a > 5) | (a == 5)
five_up    # will check the condition whether that number satisfies the condition or not


array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [25]:
a[:, np.newaxis]


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [26]:
a.sum()

66

In [27]:
a.mean()

6.0

In [38]:
a[:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])